### ISSUE TITLE
Design is broken in production

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#111]
## About

Our front-end design in production is completely different than what I've designed initially. We should be more careful when porting the implemented HTML files to Django templates and _not dramatically change it_.

### Signup page
(Note that the heading is also wrong - it says `Login`)
![screen shot 2017-11-01 at 10 42 57](https://user-images.githubusercontent.com/13895224/32264959-15eedcde-bef2-11e7-94b4-94a2e0a8dfe4.png)

Initial design:
![screen shot 2017-11-01 at 10 42 58](https://user-images.githubusercontent.com/13895224/32264960-16108104-bef2-11e7-8c41-f3c2c2700e52.png)

### Login page
![screen shot 2017-11-01 at 10 41 53](https://user-images.githubusercontent.com/13895224/32264961-162fab7e-bef2-11e7-8a78-57d668ec2764.png)

Initial design:
![screen shot 2017-11-01 at 10 41 51](https://user-images.githubusercontent.com/13895224/32264962-164c5ca6-bef2-11e7-907a-7ce9fd3b0d2d.png)

## Environment
macOS 10.13, Safari 11

## To-do

- [ ] Fix the heading on the signup page.
- [ ] Fix the design of the inputs and texts.
- [ ] Since I couldn't register (see #110 for details) I couldn't check the design of the other pages. Possibly they are also broken, so check and fix them as well.

**Comment by smddzcy** [comment]
It's just a copy paste, I have no idea how things went this wrong 😄 Please be more careful when approving PRs as well.

**Comment by karacasoft** [comment]
We may have let Django do the form generation thing. I'll fix it after the milestone, and after that, please do not EVER give me any job that is not related to Android.

**Comment by smddzcy** [comment]
It's better if @yfenes can fix this, he's the one who wrote the login & register backend. I assigned it to you because I remembered you were the reviewer of this feature but I didn't have the time to check who actually implemented it 😄

**Comment by karacasoft** [comment]
We never requested front-end from him, he was pretty busy at that moment and his code was actually ok. So I accepted his changes

**Comment by Morgazipa** [comment]
I tried the fix the issue, see my pull request.
