### ISSUE TITLE
Join/leave group functionality on web-frontend

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2017group5#124]
## About

Join/leave group functionality is to be integrated to the web-frontend of our project, as per [18th meeting notes](../wiki/Meeting-18-07.11.2017).

## To-do

- [x] Extend the `templates/views.py` to give us the required information.
- [x] Query the status of the user with respect to the group, i.e. joined or not.
- [x] Make a request to the backend API to join or leave the group.
- [x] Change the text in the button as well as its functionality, depending on the user's current state.

**Comment by ThoAppelsin** [comment]
I have completed it. Very much thanks to Mahmut for his helps on answering my questions.

We also have made it so that the button has a different color for Join and Leave Group.
