### ISSUE TITLE
Prepare a News Feed page on the web frontend

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2017group5#126]
## About

We have to prepare a News Feed page for our web-frontend, as per [18th meeting notes](../wiki/Meeting-18-07.11.2017).

## To-do

- [x] Create a `news.html` template and a class in `views.py`, then an association in `urls.py`.
- [x] Design a news feed page for the logged-in user to land.
- [ ] Implement its views.
- [ ] Implement its templates.
- [x] Add news feed page to the navigation dropdown.

**Comment by ThoAppelsin** [comment]
I don't really know how the news feed page should be. I have created a template page for it, made a basic view, but couldn't proceed.

**Comment by ThoAppelsin** [comment]
This was done too, I guess.
