### ISSUE TITLE
Prepare web-frontend elements for template creation, viewing, usage and posting

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2017group5#127]
## About

As per [19th meeting notes](../wiki/Meeting-19--14.11.2017), we have to integrate the template functionalities from backend to the web-frontend.

We have agreed to give ourselves one week to implement it. However, it would be really good if we were to do it until 13:00 this Thursday (16 November), as promised to our customer. It isn't likely to happen, since we have only ~38 hours left, and two nights to sleep.

## To-do

- [x] Template creation view.
- [x] Listing of templates per group.
- [x] Template selection and activation.
- [x] Template posting.

**Comment by smddzcy** [comment]
I'll implement these on Wednesday evening if no one else (_current assignees_) does it by then.

**Comment by ThoAppelsin** [comment]
I have done many of these by writing several lines of JS code, around 300~400 lines, hardly ever commented. As a summary, a user may do the followings on the `webfrontend_2` branch:

- Create a new template through the "Create a template" modal, inside:
  - Add one of the three template fields, Checkbox, Multiple Selection, or Text Area, via the "+" button,
  - Add as many fields as they want
  - With their labels, they can,
    - Start editing them by clicking on them
    - Finish editing them by clicking away, or hitting Enter key
  - Remove the fields through the close symbol to the right
  - Submit the template through the "Create!" button
- Select a different template from the dropdown list to see it

On the other hand, there are several shortcomings, including the following:
- The style is just horrible.
- The whole JavaScript code resides on the `group-details.html`, and probably needs to be imported as an external resource from a `static` directory, or whatever.
- For the fields:
  - Multiple Selection field is for now a multiple selection of three checkboxes. In the script, it is very easy to make it of any other number, just add more labels. The frontend functionality is not there yet.
  - There are several other field types we should be offering, and their drafts are available as a comment towards the end of the `group-details.html`.
- For editing and extending templates, the buttons are there, but the functionality isn't.
- User cannot yet share a post made out of a template.
- A malicious user may just create hundreds of templates.

Feel free to improve these points or improve in any way you can imagine. Make sure to pull before doing any work.
