### ISSUE TITLE
Implement profile page

### ISSUE THREAD

**Issue by oal55** [bounswe/bounswe2017group5#142]
## About

As briefly discussed after the class today, we should implement CRUD operations of a profile page.

### Things I have in mind:

- UserProfile object will have the following fields; 
  * name
  * surname
  * date of birth
  * location
  * interests
- It will have a 1-to-1 relationship with our user object.

Any insights would be much appreciated. 

## To-do
- [x] Implement a ProfilePage model.
- [x] Implement ProfilePage serializer & views
- [x]  Implement ProfilePage tests.
