### ISSUE TITLE
Prepare presentation for Milestone 2

### ISSUE THREAD

**Issue by iremUlutas** [bounswe/bounswe2017group5#146]
## About

* **Related Issues:** ...

Prepare a presentation about the improvements of the project since the last milestone.

## To-do
- [x] Clarify what was expected.
- [x] Create a list of improvements.
- [x] Prepare a slide on Google Slides.

**Comment by smddzcy** [comment]
What is expected:

- [x] Template create / use (use: #149, create: #139)
- [x] Semantic tagging (currently very limited, tags can be added only on group creation, see: #151)
- [x] User profile (seems to be working #142 )
- [x] Search group / user backend (text based, by group name and user name, #140 )
- [x] Search group / user frontend (#158)
- [ ] Content recommendation (backend: #141)
- [x] Comment on posts (frontend:#155, backend: #137 )
- [x] Post votes (up or down)

**Comment by smddzcy** [comment]
Backend slides are (almost) done 👌  I need rest of the features (recommendations, votes, profile) to be merged & deployed.

**Comment by oal55** [comment]
Profile page is done, waiting for PR review.
