### ISSUE TITLE
Create use-case scenarios with the latest version for milestone presentation

### ISSUE THREAD

**Issue by iremUlutas** [bounswe/bounswe2017group5#147]
## About

* **Related Issues:** #146

As the milestone presentation's approaching, we need various use-cases to show off with the latest version of the app. 

## To-do
- [x] Generate use case scenarios containing the improvements of the project since the first milestone.
- [x] Create database entities according to the scenarios.
- [ ] Practice the scenario until the presentation at least twice.
