### ISSUE TITLE
Creating an isolated backend for annotations

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#181]
## About

* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Milestone-2-Report

We should create an isolated backend for annotations. The API should implement the [Web Annotation Protocol](https://www.w3.org/TR/annotation-protocol/), and ideally, we should create a separate DB for this API as suggested by Suzan Uskudarli many times.

## To-do

- [ ] Create an isolated team for this task
- [ ] Discuss the API and DB structure
- [ ] Implement the API

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group5 Any volunteers for the annotations team?

**Comment by Morgazipa** [comment]
I would like to help.

**Comment by smddzcy** [comment]
@Morgazipa Awesome 👍 Can you please do some research and create a basic roadmap? (e.g. what/how to do, how many people is required etc.)

**Comment by oal55** [comment]
I'd like to help as well.

**Comment by smddzcy** [comment]
So, where are we on this one? We should make some progress as the deadline is approaching :)

**Comment by murat0431** [comment]
I'd like to help with this as well. Where are we?

**Comment by Morgazipa** [comment]
Reading W3C annotation model document, I think the following are valid DB models:

Annotations on text:
``` 
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://interestr.com/annotations/{id}",
  "type": "Annotation",
  "created": "2015-01-28T12:00:00Z",
  "creator": {
    "id": "http://interestr.com/profile/{id}",
    "type": "Person",
    "name": "{firstname} {lastname}",
    "nickname": "{username}",
    "email": "{email}"
	},

  "bodyValue": "Annotation text",
  "target": {
    "source": "http://interestr.com/posts/{id}",
	"type": "Text",
     "selector": {
      "type": "XPathSelector",
      "value": "/html/body/p[2]/table/tr[2]/td[3]/span",
	  "refinedBy": {
		  "type": "TextPositionSelector",
		  "start": 412,
		  "end": 795
    }  
    }
  }

}
```

Annotations on images
``` 
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://interestr.com/annotations/{id}",
  "type": "Annotation",
  "created": "2015-01-28T12:00:00Z",
  "creator": {
    "id": "http://interestr.com/profile/{id}",
    "type": "Person",
    "name": "{firstname} {lastname}",
    "nickname": "{username}",
    "email": "{email}"
	},

  "bodyValue": "Annotation text",
  "target": {
    "source": "http://interestr.com/posts/{id}",
	"type": "Image"
     "selector": {
      "type": "XPathSelector",
      "value": "/html/body/p[2]/table/tr[2]/td[3]/span",
	  "refinedBy": {
		  "type": "FragmentSelector",
		  "conformsTo": "http://www.w3.org/TR/media-frags/",
		  xywh=50,50,640,480

    }  
    }
  }

}
```

**Comment by ThoAppelsin** [comment]
Not that I am 100% ready and only waiting for this, but it would help to have it sooner than later. Right now, I am developing in the whereabouts of my own imagination of what I would probably have as an API, for the Firefox add-on I mean (#182).

**Comment by Morgazipa** [comment]
This is done.
