### ISSUE TITLE
Preparing a system manual

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#192]
## About

As per our final deliverables, we need to provide a system manual with our software that describes the system requirements and installation (i.e. setup). There should be separate sections for the backend, frontend, and Android application.

## To-do

- [x] Manual for backend setup
- [x] Manual for frontend setup (if there is any)
- [x] Manual for Android setup

**Comment by karacasoft** [comment]
https://github.com/bounswe/bounswe2017group5/tree/package

Maybe merging this into master is not a good idea. Have done some packaging which also includes setup instructions. Please check. Instruction mention about a project deployment document which I'll create soon.

**Comment by smddzcy** [comment]
Looks good, closing this one 👌 Link to the document: https://docs.google.com/document/d/1ztY9P1DAj2lUaNmG7fClTZFhxiz-VKESpST4rXiQP2Q/edit#
