### ISSUE TITLE
Generate realistic content

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#195]
## About

We should generate some _realistic_ content (**at least 100 items**) in our production app to jumpstart crowdsourcing & recommendation system.

## To-do

- [x] Create realistic users.
- [x] Create realistic groups with some users joined.
- [x] Create realistic data templates and posts.

**Comment by yfenes** [comment]
Realistic user ve groups are created.
Team members can access the credentials with help of the link shared in Slack.

**Comment by smddzcy** [comment]
Thanks a lot 👍

**Comment by smddzcy** [comment]
@murat0431 Will you be able to handle the data templates and posts?

**Comment by murat0431** [comment]
Yeah.Tomorrow evening i will start to create realistic templates and posts.I thought every user 
might have 4-5 templates and 4-5 posts in total.Thus every group will have 9-10 posts approximately.

**Comment by smddzcy** [comment]
Sounds good 👌

**Comment by murat0431** [comment]
I have created realistic templates and posts. Since it is not necessary anymore, I am closing this issue.
