### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group5#57]
Update names in the project plan considering new team members.

**Comment by yfenes** [comment]
Done.

**Comment by esra-aydemir** [comment]
We need to update project plan before milestone 2. Any volunteers?

**Comment by esra-aydemir** [comment]
Apparently we do not plan to update the plan but rather than that explaining our work to customer depending on the available plan. It is important that all teams follow what is done and what is in the plan. Check below if you feel like you and your team can present your teams work by comparing with the project plan.

- [ ] Android team @triforce930 
- [x] Backend team @smddzcy 
- [ ] Frontend team @Morgazipa

**Comment by smddzcy** [comment]
We should update the plan at some point. @bounswe/bounswe2017group5 any volunteers?

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group5 It's urgent now - we should update our project plan **in 2 days.**
