### ISSUE TITLE
Create the new project plan

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#69]
## About

* **Related Issues:** #57 
* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Project-Plan

Although updated recently (with #57), our existing project plan is very inaccurate. We should create a new plan, from scratch, because we don't have it in an editable format.

## Visuals

Nothing is created yet, will put some visuals once it's done.

## To-do

- [x] Choose a platform to create a maintainable project plan.
- [x] Create the new project plan
  - [x] Divide the project into small subprojects, and then into small tasks
  - [x] Assign these tasks to specific people (e.g. frontend, backend, mobile)
- [x] Create the milestones for the backend
- [x] Create the milestones for the frontend (as soon as we choose a framework)
- [x] Create the milestones for the Android app (someone else should do it)

**Comment by smddzcy** [comment]
Here are the tasks (thanks to @triforce930) of our new project plan:
[frontend.txt](https://github.com/bounswe/bounswe2017group5/files/1357099/frontend.txt)
[backend.txt](https://github.com/bounswe/bounswe2017group5/files/1357097/backend.txt)

**Comment by smddzcy** [comment]
Here is our new project plan:
![project-plan](https://user-images.githubusercontent.com/13895224/31200567-1e0d78ba-a964-11e7-94b2-28f46f0c3a67.jpg)

Notes:
- I have no experience in Android development, so I left the time blocks blank for the Android tasks. @triforce930 is needed here 👍 
- I'll create the milestones for the frontend once we choose a framework, but someone else should do the Android part.
- We should discuss about task assignment in our next meeting. As you can see, there are parallel tasks in the project plan both for the backend and the frontend tasks. We need at least `max(# of parallel tasks at any given time) + 1` people in each team to stick with the timeline. (+1 is the backup person, who can work in another team but would be willing to help when needed)
  - Which means 4+1 backend and 2+1 frontend with this plan.

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group5 Can everyone assign themselves to a few non-conflicting tasks?

**Comment by karacasoft** [comment]
I have added the time schedule + milestones for Android. Requesting review now...

**Comment by smddzcy** [comment]
@triforce930 It looks perfect... 😅  I also updated the frontend tasks and milestones. The only thing left is to assign these to some people.

**Comment by karacasoft** [comment]
Didn't I have already done that? :V

**Comment by karacasoft** [comment]
Maybe it's best if we do the assignments as we go and don't waste time assigning far away tasks to some people who we don't even know if he/she wants the task or not.

**Comment by smddzcy** [comment]
@triforce930 Agreed, closing since it's done.
