### ISSUE TITLE
Create a server in Amazon

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#72]
## About

As discussed today, I'll create a server in Amazon to deploy our application.

## To-do

- [x] Create an Ubuntu server in Amazon EC2.
- [x] Set up the server.
- [x] Share the ssh key with the team.
