### ISSUE TITLE
Customer Meeting - 19/10/17

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#75]
## About

We had a conversation with our customer in the lecture hour. These are the notes from that conversation.

### Web
- Group create & read endpoints and its views
- Post create & read endpoints
- Default data template(s)

### Android
- Group list view

## Presentation
Our first presentation on **2nd of November** will be **20 mins** - most of it will be a demo. We should at least put these into our presentation:
- Requirements - 2 slides
- Semantic tagging - 1 slide
- Important revisions
- Lessons learned - 1-2 slide
- Planned vs Done - 1 slide

## To-do

- [x] Restrict input types in data templates and put it into requirements.
- [x] Think about semantic tagging - use 3rd-party APIs like Wikidata for it. Also put in into requirements.
- [x] Add the official milestones to the project plan.
  - [x] Add an intermediate milestone just before the first milestone to show the basics to our customer.

**Comment by smddzcy** [comment]
Discussed with @triforce930 and decided we should allow these data types in data templates:
- Short text (`<input type="text">...`)
- Long text (`<textarea>...</textarea>`)
- Single choice (`<select>...</select>`)
- Multiple choice (`<select multiple>...</select>`)
- Date (`<input type="date">...`)
- Numeric (`<input type="number">...`)
- Email (`<input type="email">...`)

If we can finish everything on time, possible extension: **Allowing other data templates as data types**, i.e. allowing nested data templates.

**Comment by karacasoft** [comment]
Wiki-data query service link:
https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help
