### ISSUE TITLE
Weekly Work Plan

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#78]
## About

We have two weeks for the next milestone.

_As we come closer to the end, we become more distressed each day, screaming "What do I do?" to each other, while running across the endless floors of the building._

**But, do not worry.** I have prepared a work plan that will save us all from this _darkness_.

You'll just have to take some of the jobs I've mentioned below. Please do not make me use random.org and take your jobs (or let us know that you're busy) as soon as possible.

### Backend
This section will include the back-end jobs that has to be done.
- [x] Token authentication / authentication endpoints (taken by Mahmut)
- [x] Group Model (taken by Orbay)
- [ ] Data Template Model and endpoints
- [x] Post Model (requires DataTemplate model) (Irem's intending)

### Frontend
This is the section that will interest the front-end developers. We are going to design pages with dummy data. Then integrate them with the back-end next week.
- [ ] Homepage
- [ ] Login/Register Pages
- [ ] Create a Group Page
- [ ] Groups Page
- [ ] Group Detail Page

### Android
We'll not write Android code this week. For this week, I'll setup my Android Development environment. Next week, when the API endpoints are finished.

**Remember:** This is a plan for this week, but code reviews are scary. If I see a flaw in your code. I'll reject it and will want you to rewrite it. For the plan to work, please do your job as soon as possible.

Have a good day!

**Comment by iremUlutas** [comment]
I might volunteer for Post Model, but a little bit of clarification would be just great.

**Comment by karacasoft** [comment]
My intention was to use this yesterday, but I decided to wait for a while. But, you've actually made me do this anyways. Here are the random.org results:
![randomorg_results](https://user-images.githubusercontent.com/5247569/31854407-2390fcd6-b6a1-11e7-9d5d-d8416a2061d1.png)

In this case, 
* Ramazan will be doing the Data Template model and endpoints
* Samed and Enes will be working on the Frontend
  * Samed will have the first three pages, others are left to Enes

Other people consider yourselves lucky, **FOR NOW!!**

I'll require these to be finished until Wednesday evening. Please don't forget to work on your own branch. Questions on Slack are always welcome.

**Comment by karacasoft** [comment]
After carefully inspecting the project plan, I realized @ThoAppelsin was actually volunteered for Data Templates job. I'm so sorry for this to happen. I'm assigning @ThoAppelsin to the Data Templates job. Please follow #81 for more details.

**Comment by karacasoft** [comment]
I'm closing this, as there's no need for this to be kept open.
