### ISSUE TITLE
Prepare the presentation for demo day

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#93]
## About

- **Related Issues**: #75

We must prepare a **collaborative presentation** for our demo day until Wednesday, **1st of November**. Everyone should prepare the pages they'll present and non-presenters should help with the general content & reviews & fixes.

## To-do

- [X] Choose the tool for creating the presentation.
- [x] Choose a presentation template. 
- [x] Fill in content. Make sure that we include the required stuff (see #75 for details).
- [x] Review and make final touches.

**Comment by smddzcy** [comment]
I think Google Slides is the perfect tool for a collaborative presentation, so the tool is chosen (if no one complains 🤐): https://docs.google.com/presentation/u/0/

**Comment by iremUlutas** [comment]
starting a slack channel to make the presentation related communication easier.

**Comment by iremUlutas** [comment]
@smddzcy The link you shared takes me to the generic Google Slides site. If this was meant to be the link to our presentation, please update it.
